language: node_js
node_js:
- lts/*
notifications:
  slack:
    secure: SHSv033RFw7FvvIWmu8CGX84zkLHaBYdPIk41zAqAuMvWCkEYHlRaaN+T0dvJxG/H2O7FJxkhHi4Wk4bHGn4W5OhL9ZwULi1QUTaxllEUxjPO0jChP9vyR4rJqkF0YshicLMdbcNrXyR4/vpjYp7/nipfCR8UysMQcRUjXm/DTjUO4akBhEHACGd/yAbLBxiXDJqhv3Z2IDHb9m6qfaPIKC1MOiCebiGNoYTGPqgfZzE8+VN0fLOnGjhR3tyXmFesFnVe4xx5uWiv6ZvaQRDMPtjLHlgOMwiv/G6OnreZFO197NUkg8IQO19HPp6pNG7PbsEBdPNclChN/EpmQkqE9Bo5AM/nruL/SixGXmsjNMnwWQgXOpwXUp5YXseeMt4gfFDjev+BpZ49o0XzGypJpp7lUfhmf4I+WDt15CcjNtkqHqF+WrCmIyEEgYVyaUO45q4EEIiMkgcRW6OCTiWhF12nWaVmtyg2DbbeqH30WauVwrqtNAklKbmC4+OANgZUIT8ehA1uGL2mPnwihtXPWsT6CsziqVOyYQYNNxyKn1yz0kzsirpZArftH3NrxsDgCClv8Ia7Q+PF1IN1YW6/NCF6E3v8dCNtP9Y3bhQxRHsT6n3q+B/cqItqlH6iKlF6atw4NWmMI0627EHcvf2PSvF15qlDJ3kCnyvtae9wpA=
